Portfolio: details popup window PR
WalterOkumu/walter-okumu-portfolio pull request #11
Opened 2022-07-21 22:13 UTC by WalterOkumu

- Changed Works Section to populate dynamically using JS
- Added pop up window to display the various work cards
- Adjusted css using media queries to change based on mobile or desktop view

2022-07-21 22:47 UTC, BertrandConxy requested changes
Hi @WalterOkumu ✋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💪 
- Project works on my PC
- no linter errors
- Use of JS ES6
- descriptive PR


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-21 22:47 UTC, BertrandConxy commented on scripts/projectsPopUp.js
> +// }
- [ ] It is important to note that commented unused codes don't look good in your codebase, which makes it difficult to read and understand. Please remove all commented codes in your codebase 😉 👍 🏃

2022-07-21 22:47 UTC, BertrandConxy commented on css/styles.css
> +}
- [ ] Good job so far 👏 👏.  The popup is rendered well. In addition to what you have done, I would suggest you to add the correct styles to your popup in order to match the Figma design. First of all, there is a dark blurred background behind the popup model which I think is very important because it keeps the model in focus. So please do your best to implement it 😃 take a look at the comparison below 👇 
**Figma**
![image](https://user-images.githubusercontent.com/90222110/180326247-6b4ac7cf-683a-4c03-9561-8d5ab359c3f9.png)
**Your design**
![image](https://user-images.githubusercontent.com/90222110/180326360-d829ab7e-5c28-4d6d-a17c-87410774b09b.png)

2022-07-21 22:47 UTC, BertrandConxy commented on css/styles.css
> +}
- [ ] In addition to that, You can see **that your popup model has a vertical scrollbar which is not on the Figma design** and I think it would be better if you resize your image so as to make everything fit well on the current window screen then after you add a property **to hide the scrollbar** 😺 😎.

2022-07-21 22:47 UTC, BertrandConxy commented on css/styles.css
> +  box-shadow: 0 48px 48px rgba(37, 47, 137, 0.08);
- [ ] The popup is working well which is good 👏. However, **it has to be responsive too**. That means it is displayed very well on both big screens and small screens. Please make **your popup displayed well on mobile screens** because as you can see in the screenshot below 👇 It is not looking well
![image](https://user-images.githubusercontent.com/90222110/180327216-abacd1c3-9565-4ca2-b1c0-db0a609c8f30.png)

💡 **HINT:** You can refer to the Figma design given. Look at the screenshot below 👇 
![image](https://user-images.githubusercontent.com/90222110/180327404-abe5fed5-2cd4-4701-aebc-533453953564.png)

2022-07-22 12:42 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/93039359/178569876-9fcda5e8-6819-4569-95ee-acb393903a05.jpg)

### Hey  @GordonOtieno :wave:

### Highlights :1st_place_medal:
 
:heavy_check_mark: Following HTML, CSS best practices
:heavy_check_mark: Following Project Requirements
:heavy_check_mark: Descriptive PR title
:heavy_check_mark: Descriptive PR summary

Good job on implementing some of the changes requested by the previous reviewer, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional suggestions
**[Optional]**
- [ ] It would be better if you would choose a descriptive name for your branch because your branch name tells what is happening in this branch and also it shows your professionalism. :blush:

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @HAMMAS-SALEEM in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-22 12:42 UTC, HAMMAS-SALEEM commented on scripts/projectsPopUp.js
> +  projectModal.appendChild(modalContent);
### Your Design
![student-design](https://user-images.githubusercontent.com/93039359/180439476-fd062af0-64a7-4d99-987e-a41319831dc3.png)

### Figma Design with corrections
#### 1.
![figma (copy)](https://user-images.githubusercontent.com/93039359/180440001-27177329-b24f-4038-bb27-84816fadda2d.png)
#### 2.
![figma (another copy)](https://user-images.githubusercontent.com/93039359/180440021-f1c8c8c6-3fa2-42c9-b997-e7af6e2f9627.png)
#### 3.
![figma (3rd copy)](https://user-images.githubusercontent.com/93039359/180441088-b79d40ac-34e9-4ed0-90f2-3fb69d32a0f5.png)


- [ ] Your model is good :blush: but there are minor changes you need to do which are shown in the images above :arrow_up:

2022-07-22 15:10 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @WalterOkumu ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Descriptive Pull Readme ✔️
- Professional Readme ✔️
- Linters are passing ✔️

## Optional suggestions

- [ ] [Optional] You may kindly remove this line from your popup design as it is not part of the Figma design.
![line](https://user-images.githubusercontent.com/63917725/180467329-3cf4b3e1-2461-4812-bc7f-81a514cfb673.PNG)


##### _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

##### Cheers and Happy coding!:clap::clap::clap:
##### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-22 15:10 UTC, 1GORDON commented on css/styles.css
> +}
Great job @WalterOkumu 🤝

- [ ] [Optional] Kindly implement the button interactions of hover and enable of the popup designs as specified in the project requirements.

2022-07-22 15:12 UTC, merged